catches/urls.py
from django.urls import path
from . import views

urlpatterns = [
     path('', views.CatchesList.as_view(), name='home'),
     path('add_catch/', views.add_catch, name='add_catch'),
     path('my_catches/', views.my_catches, name='my_catches'),
     path('edit_catch/<slug:slug>/', views.edit_catch, name='edit_catch'),
     path(
        'delete_catch/<slug:slug>/',
        views.delete_catch,
        name='delete_catch'
        ),

     path('<slug:slug>/', views.catch_detail, name='catch_detail'),
     path('<slug:slug>/edit_comment/<int:comment_id>',
          views.comment_edit, name='comment_edit'),
     path('<slug:slug>/delete_comment/<int:comment_id>',
          views.comment_delete, name='comment_delete'),
]

fished_it/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("my_profile/", include("my_profile.urls")),
    path("", include("catches.urls")),
    path("accounts/", include("allauth.urls")),
]

catches/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from autoslug import AutoSlugField


class Catch(models.Model):
    STATUS = ((0, "Private"), (1, "Public"))
    """
    Stores a single blog catch entry related to :model:`auth.User`.

    Attributes:
        fish_species (CharField): The species of the caught fish.
        fish_length (FloatField): The length of the caught fish.
        fish_weight (FloatField): The weight of the caught fish.
        author (ForeignKey to User): The user who caught the fish.
        featured_image (CloudinaryField): The image of the caught fish.
        created_on (DateTimeField): The timestamp when the catch entry
        updated_on (DateTimeField): The timestamp when the catch entry
        public (IntegerField): Indicates whether the catch entry is
    """
    objects = models.Manager()
    fish_species = models.CharField()
    fish_length = models.FloatField()
    fish_weight = models.FloatField()
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="catch_posts"
        )

    featured_image = CloudinaryField('image', default='placeholder')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    public = models.IntegerField(choices=STATUS, default=0)
    slug = AutoSlugField(populate_from='fish_species', unique=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.fish_species} caught by {self.author}"


class Comment(models.Model):
    """
    Stores a single comment entry related to :model:`auth.User`
    and :model:`catches.Catch`.

    Attributes:
        post (ForeignKey to Catch): The catch to which the comment belongs.
        author (ForeignKey to User): The user who wrote the comment.
        body (TextField): The content of the comment.
        created_on (DateTimeField): The timestamp when the comment was created.
        approved (BooleanField): Indicates whether the comment
        is approved or not.
    """
    post = models.ForeignKey(
        Catch,
        on_delete=models.CASCADE,
        related_name="comments"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="commenter"
    )
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.author}"

catches/forms.py
from django import forms
from .models import Comment, Catch


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class CatchForm(forms.ModelForm):
    class Meta:
        model = Catch
        fields = [
            'fish_species',
            'fish_length',
            'fish_weight',
            'featured_image',
            'public'
        ]
        widgets = {
            'fish_species': forms.TextInput(attrs={'class': 'form-control'}),
            'fish_length': forms.NumberInput(attrs={'class': 'form-control'}),
            'fish_weight': forms.NumberInput(attrs={'class': 'form-control'}),
            'featured_image': forms.ClearableFileInput(
                attrs={'class': 'form-control'}
            ),
            'public': forms.Select(
                choices=Catch.STATUS, attrs={'class': 'form-control'}
            ),
        }

catches/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .forms import CommentForm, CatchForm
from .models import Catch, Comment


class CatchesList(generic.ListView):
    queryset = Catch.objects.filter(public=1)
    template_name = "catches/index.html"
    paginate_by = 6


def catch_detail(request, slug):
    """
    Display an individual :model:`catches.catch`.

    **Context**

    ``catch``
        An instance of :model:`catches.catch`.

    **Template:**

    :template:`catches/catch_detail.html`
    """

    queryset = Catch.objects.filter(public=1)
    catch = get_object_or_404(queryset, slug=slug)
    comments = catch.comments.all().order_by("-created_on")
    comment_count = catch.comments.filter(approved=True).count()
    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = catch
            comment.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Comment submitted and awaiting approval'
            )

    comment_form = CommentForm()

    return render(
        request,
        "catches/catch_detail.html",
        {
            "catch": catch,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form,
        },

    )


def comment_edit(request, slug, comment_id):
    """
    view to edit comments
    """
    if request.method == "POST":

        queryset = Catch.objects.filter(public=1)
        post = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, 'Comment Updated!')
        else:
            messages.add_message(
                request,
                messages.ERROR,
                'Error updating comment!'
            )

    return HttpResponseRedirect(reverse('catch_detail', args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    view to delete comment
    """
    queryset = Catch.objects.filter(public=1)
    post = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, 'Comment deleted!')
    else:
        messages.add_message(
            request,
            messages.ERROR, 'You can only delete your own comments!')

    return HttpResponseRedirect(reverse('catch_detail', args=[slug]))


@login_required
def add_catch(request):
    if request.method == "POST":
        form = CatchForm(request.POST, request.FILES)
        if form.is_valid():
            new_catch = form.save(commit=False)
            new_catch.author = request.user
            new_catch.save()
            messages.add_message(
                request, messages.SUCCESS,
                'Catch successfully added'
            )
            return redirect('home')
    else:
        form = CatchForm()

    return render(request, "catches/add_catch.html", {"form": form})


@login_required
def my_catches(request):
    my_catches = Catch.objects.filter(author=request.user)
    return render(request, 'catches/my_catches.html', {'catches': my_catches})


@login_required
def edit_catch(request, slug):
    catch = get_object_or_404(Catch, slug=slug, author=request.user)
    if request.method == 'POST':
        form = CatchForm(request.POST, request.FILES, instance=catch)
        if form.is_valid():
            form.save()
            messages.success(request, 'Catch updated successfully.')
            return redirect('my_catches')
        else:
            messages.error(request, "Uh oh! Catch wasn't updated :(")
    else:
        form = CatchForm(instance=catch)
    return render(
        request,
        'catches/edit_catch.html', {'form': form, 'catch': catch})


@login_required
def delete_catch(request, slug):
    catch = get_object_or_404(Catch, slug=slug)

    if request.user == catch.author:
        catch.delete()
        messages.success(request, 'Catch deleted successfully.')
    else:
        messages.error(request, 'You can only delete your own catches.')

    return redirect('my_catches')

catches/templates/catches/add_catch.html
{% extends "base.html" %}  <!-- or your base template -->
{% block content %}
<div class="container mt-4">
    <h2>Add Catch</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-signup">Submit</button>
    </form>
</div>    
{% endblock %}

catches/templates/catches/catch_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="masthead">
    <div class="container">
        <div class="row g-0 stack">
            <div class="col-md-6 masthead-text">
                <h1 class="catch-title">{{ catch.fish_species }}</h1>
                <p class="catch-subtitle">Caught by {{ catch.author }} on {{ catch.created_on }}</p>
                <p class="catch-subtitle">Size: {{ catch.fish_length }} cm</p>
                <p class="catch-subtitle">Weight: {{ catch.fish_weight }} kg</p>
              </div>
            <div class="d-md-block col-md-6 masthead-image">
              {% if "placeholder" in catch.featured_image.url %}
              <img class="card-img-top" src="{% static 'images/default.jpg' %}"
                alt="placeholder image">
              {% else %}
              <img class="card-img-top" src=" {{ catch.featured_image.url }}"
                alt="{{ catch.title }}">
              {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container seperation">
      <!-- Displaying count of comments -->
  <div class="row">
    <div class="col-12">
      <strong class="text-secondary">
        <i class="far fa-comments"></i> {{ comment_count }}
      </strong>
    </div>
    <div class="col-12">
      <hr>
    </div>
  </div>
  <!-- Displaying Comments -->
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 ">
      <h3>Comments:</h3>
      <div class="card-body">
        <!-- We want a for loop inside the empty control tags
          to iterate through each comment in comments -->
        {% for comment in comments %}
        <div class="p-2 comments
          {% if not comment.approved and comment.author == user %}
          faded{% elif not comment.approved %} d-none{% endif %}">
          <p class="font-weight-bold">
            {{ comment.author }}
            <span class="font-weight-normal">
              {{ comment.created_on }}
            </span> wrote:
          </p>
          <div id="comment{{ comment.id }}">
            {{ comment.body | linebreaks }}
          </div>
          {% if not comment.approved and comment.author == user %}
          <p class="approval">
            This comment is awaiting approval
          </p>
          {% endif %}
          {% if user.is_authenticated and comment.author == user %}
          <button class="btn btn-delete"
            comment_id="{{ comment.id }}">Delete</button>
          <button class="btn btn-edit"
            comment_id="{{ comment.id }}">Edit</button>
          {% endif %}
        </div>
        <!-- Our for loop ends here -->
        {% endfor %}
      </div>
    </div>
    <!-- Creating New Comments -->
    <div class="col-md-4 card mb-4 mt-3">
        <div class="card-body">
            {% if user.is_authenticated %}
              <h3>Leave a comment:</h3>
              <p>Posting as: {{ user.username }}</p>
              <form id="commentForm" method="post"
                style="margin-top: 1.3em;">
                {{ comment_form | crispy }}
                {% csrf_token %}
                <button id="submitButton" type="submit"
                  class="btn btn-signup btn-lg">Submit</button>
            </form>
            {% else %}
            <p>Log in to leave a comment</p>
            {% endif %}
        </div>
    </div>
  </div>
</div>

<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
  aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extras %}
<script src="{% static 'js/comments.js' %}"></script>
{% endblock %}

catches/templates/catches/catches_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Views Part 1</title>
</head>

<body>
    <h1>Catches list</h1>
    {% for catch in object_list %}
    <h2>{{catch.fish_species}}</h2>
    <p>Length: {{catch.fish_length}}, Weight: {{catch.fish_weight}}</p>
    <p>Caught by: {{catch.author}}</p>
    {% endfor %}
</body>

</html>

catches/templates/catches/edit_catch.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-4">
    <h2>Edit Catch</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-signup">Save Changes</button>
        <a href="{% url 'my_catches' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

catches/templates/catches/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Introduction Section -->
<div class="container mt-3">
    <div class="row">
        {% if not user.is_authenticated %}
        <div class="col-12">
            <div class="alert alert-info" role="alert">
                <h4 class="alert-heading">Welcome to Our Fishing Community!</h4>
                <p>We invite you to join our community to share your fishing experiences, connect with other anglers, and keep track of your catches. Registering an account allows you to create your own fishing diary and interact with fellow fishing enthusiasts.</p>
                <hr>
                <p class="mb-0">Don't miss out on the fun – <a href="{% url 'account_signup' %}">Register Now</a>!</p>
            </div>
        </div>
        {% endif %}
    </div>
</div>

<!-- Catch Entries Column -->
<div class="container-fluid mt-3">
    <div class="row">

        <div class="col-12 mt-3 left">
            <div class="row">
                {% for catch in catch_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                <a href="{% url 'catch_detail' catch.slug %}" class="card-link">
                                    {% if "placeholder" in catch.featured_image.url %}
                                    <img class="card-img-top" src="{% static 'images/default.jpg' %}" alt="placeholder image">
                                    {% else %}
                                    <img class="card-img-top" src="{{ catch.featured_image.url }}" alt="{{ catch.title }}">
                                    {% endif %}
                                    <div class="image-flash">
                                        <p class="author">Caught by {{ catch.author }}</p>
                                    </div>
                                </a>
                            </div>
                            <a href="{% url 'catch_detail' catch.slug %}" class="catch-link">
                                <h2 class="card-title">{{ catch.fish_species }}</h2>
                            </a>
                            <p class="card-text text-muted h6">Created on: {{ catch.created_on }}</p>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 and not forloop.last %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREVIOUS</a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock %}

catches/templates/catches/my_catches.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2>My Catches</h2>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>Image</th>
                    <th>Fish Species</th>
                    <th>Fish Length</th>
                    <th>Fish Weight</th>
                    <th>Created On</th>
                    <th>Updated On</th>
                    <th>Public</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for catch in catches %}
                <tr>
                    <td class="align-middle thumbnail-cell text-center">
                        {% if "placeholder" in catch.featured_image.url %}
                            <p class="mb-0">No image uploaded</p>
                        {% else %}
                            <img src="{{ catch.featured_image.url }}" alt="{{ catch.title }}" class="thumbnail">
                        {% endif %}
                    </td>
                    <td class="align-middle">{{ catch.fish_species }}</td>
                    <td class="align-middle">{{ catch.fish_length }}</td>
                    <td class="align-middle">{{ catch.fish_weight }}</td>
                    <td class="align-middle">{{ catch.created_on }}</td>
                    <td class="align-middle">{{ catch.updated_on }}</td>
                    <td class="align-middle">
                        {% if catch.public %}
                        Yes
                        {% else %}
                        No
                        {% endif %}
                    </td>
                    <td class="align-middle">
                        <a href="{% url 'edit_catch' catch.slug %}" class="btn btn-signup">
                            <i class="fas fa-edit"></i> Edit
                        </a>
                        <button type="button" class="btn btn-danger delete-catch" data-bs-toggle="modal" data-bs-target="#deleteCatchModal_{{ catch.id }}">
                            <i class="fas fa-trash-alt"></i> Delete
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% for catch in catches %}
    <!-- Delete Catch Modal for each catch -->
    <div class="modal fade" id="deleteCatchModal_{{ catch.id }}" tabindex="-1" aria-labelledby="deleteCatchModalLabel_{{ catch.id }}" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteCatchModalLabel_{{ catch.id }}">Delete Catch</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Are you sure you want to delete this catch?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="{% url 'delete_catch' catch.slug %}" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}